MUTAG:
  out_hidden: 64
  hidden: 32
  epochs: 100
  lr: 1e-3
  rate: 0.6
  warmup: 100
  w: 1e-5
  acc: 90.50+-8.4
  alpha: 0.3
  layer: 1
PROTEINS:
  out_hidden: 64
  hidden: 32
  epochs: 100
  lr: 1e-5
  rate: 0.3
  warmup: 100
  w: 1e-5
  acc: 75.83+-2.1
  alpha: 0.5
  layer: 2
COLLAB:
  out_hidden: 64
  hidden: 32
  epochs: 50
  lr: 1e-5
  rate: 0.9
  warmup: 100
  w: 1e-5
  acc: 78.8+-1.5
  alpha: 0.6
  layer: 2
  agg: Max
NCI1:
  out_hidden: 64
  hidden: 32
  epochs: 20
  lr: 1e-5
  rate: 0.1
  warmup: 100
  w: 1e-4
  acc: 80.97+-2.7
  alpha: 0.5
  layer: 3
IMDB-BINARY:
  out_hidden: 64
  hidden: 32
  epochs: 100
  lr: 1e-5
  rate: 0.1
  warmup: 100
  w: 5e-4
  acc: 74.8+-4.7
  alpha: 0.2
  layer: 2
IMDB-MULTI:
  out_hidden: 64
  hidden: 32
  epochs: 200
  lr: 1e-5
  rate: 0.7
  warmup: 100
  w: 1e-5
  acc: 50.8+-1.65
  alpha: 0.5
  layer: 1
  agg: Max
DD:
  out_hidden: 64
  hidden: 32
  epochs: 50
  lr: 1e-4
  rate: 0.4
  warmup: 100
  w: 1e-5
  acc: 78.61+-4.3
  alpha: 0.5
  layer: 3
REDDIT-MULTI5K:
  out_hidden: 64
  hidden: 32
  epochs: 100
  lr: 1e-3
  rate: 0.5
  warmup: 100
  w: 1e-5
  acc: 55.17+-8.4,0.7
  alpha: 0.5
  layer: 2
ENZYMES:
  out_hidden: 64
  hidden: 32
  epochs: 100
  lr: 1e-4
  rate: 0.1
  warmup: 100
  w: 1e-5
  acc: 59.3+-8.6
  alpha: 0.8
  layer: 2
PTC-MR:
  out_hidden: 64
  hidden: 32
  epochs: 50
  lr: 1e-4
  rate: 0.1
  warmup: 100
  w: 1e-5
  acc: 67.1+-8.7
  alpha: 0.2
  layer: 2
  featdim: 18
NCI109:
  out_hidden: 64
  hidden: 32
  epochs: 100
  lr: 1e-5
  rate: 0.2
  warmup: 100
  w: 1e-5
  acc: 80.2+-1.9
  alpha: 0.3
  layer: 3